package com.lic.epgs.payout.PdfServiceImpl;

import java.io.File;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.Base64;
import java.util.List;
import java.util.UUID;

import javax.transaction.Transactional;

import org.apache.commons.lang3.StringUtils;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.apache.poi.util.IOUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.core.ParameterizedTypeReference;
import org.springframework.core.env.Environment;
import org.springframework.core.io.ClassPathResource;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;
import org.springframework.web.client.HttpStatusCodeException;
import org.springframework.web.client.RestTemplate;
import org.xhtmlrenderer.pdf.ITextRenderer;

import com.lic.epgs.integration.dto.InterestFundResponseDto;
import com.lic.epgs.payout.PdfService.FundStatementPdfService;
import com.lic.epgs.policy.dto.StampDutyConsumptionRequestDto;
import com.lic.epgs.policy.repository.MemberMasterRepository;
import com.lic.epgs.utils.CommonConstants;
import com.lowagie.text.DocumentException;
import com.lowagie.text.html.HtmlEncoder;

@Service
public class FundStatementPdfServiceImpl implements FundStatementPdfService{
	
	protected final Logger logger = LogManager.getLogger(getClass());
	
	@Value("${temp.pdf.location}")
	private String tempPdfLocation;
	
	@Autowired
	RestTemplate restTemplateService;
	
	@Autowired
	Environment environment;
	
	@Autowired
	MemberMasterRepository memberMasterRepository;
	
	

	
	
	@Override
	@Transactional
	public String fundStatementPdfGeneration(String referenceNo, String reportType, String forwardTo,Long policyId,String financialYear)  throws IOException {
		InputStream islicLogo = new ClassPathResource("liclogo.png").getInputStream();
		// Uncomment below line to add watermark to the pdf
		// InputStream islicWatermark = new
		// ClassPathResource("watermark.png").getInputStream();
		byte[] bytesLogo = IOUtils.toByteArray(islicLogo);
		// Uncomment below line to add watermark to the pdf
		// byte[] bytesWatermark = IOUtils.toByteArray(islicWatermark);

		String licLogo = Base64.getEncoder().encodeToString(bytesLogo);
		// Uncomment below line to add watermark to the pdf
		// String licWatermark = Base64.getEncoder().encodeToString(bytesWatermark);

		boolean showLogo = true;
		String reportBody = "";
		String reportStyles = "";
		String htmlContent2 = "</div></body></html>"; // DO NOT DISTRUB THIS LINE
//		if (reportType.equalsIgnoreCase("claimForwardingLetter")) {
//			logger.info("claimForwardingLetter ------generateReport---Start");
//			reportBody = claimForwardingLetterContent(referenceNo) + htmlContent2;
//			showLogo = false;
		//} 
	 if (reportType.equalsIgnoreCase("fundStatementForV1AndV3")) {
			reportBody = fundStatementForV1AndV3(policyId,financialYear) + htmlContent2;
			showLogo = false;
	 }
//	 else if (reportType.equalsIgnoreCase("fundStatementForV2")) {
//			reportBody = fundStatementForV2() + htmlContent2;
//			showLogo = false;
//	 }
//		} else if (reportType.equalsIgnoreCase("payoutVoucherWithdrawal")
//				|| reportType.equalsIgnoreCase("payoutVoucherMaturity")
//				|| reportType.equalsIgnoreCase("payoutVoucherDeath")) {
//			reportBody = payoutVoucher(referenceNo, reportType) + htmlContent2;
//			reportStyles = payoutVoucherStyles();
//			showLogo = false;
//		} else if (reportType.equalsIgnoreCase("regularAdjustment")
//				|| reportType.equalsIgnoreCase("subsequentAdjustment") || reportType.equalsIgnoreCase("NB")) {
//			reportBody = adjustmentVoucher(referenceNo, reportType) + htmlContent2;
//			reportStyles = adjustmentVoucherStyles();
//			showLogo = false;
//		} else if (reportType.equalsIgnoreCase("withdrawalLetter")) {
//			reportBody = withdrawalLetter(referenceNo, reportType, forwardTo) + htmlContent2;
//			reportStyles = withdrawalLetterStyles();
//			showLogo = false;
//		}
		String completehtmlContent = "<!DOCTYPE  html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">"
				+ "<html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en\" lang=\"en\"><head><meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/><title>LIC ePGS</title><meta name=\"author\" content=\"LIC PNGS\"/><meta name=\"keywords\" content=\"Customer Communication\"/><meta name=\"description\" content=\"Report/Letter/Contract\"/><style type=\"text/css\"> body{border-width:0px;"
				+ "border-style:solid;" + "border-color:#586ec5;} * {margin:0; padding:0; text-indent:0; }"
				+ " .s1 { color: #2E5396; font-family:\"Times New Roman\", serif; font-style: normal; font-weight: normal; text-decoration: none; font-size: 16pt; }"
				+ " .s2 { color: #2E3599; font-family:\"Times New Roman\", serif; font-style: normal; font-weight: normal; text-decoration: none; font-size: 12pt; }"
				+ " p { color: black; font-family:\"Times New Roman\", serif; font-style: normal; font-weight: normal; text-decoration: none; font-size: 10pt; margin:0pt; }"
				+ " .a { color: black; font-family:\"Times New Roman\", serif; font-style: normal; font-weight: normal; text-decoration: none; font-size: 12pt; }"
				+ " .s3 { color: black; font-family:\"Times New Roman\", serif; font-style: normal; font-weight: normal; text-decoration: none; font-size: 12pt; }"
				+ " .s5 { color: #2E3599; font-family:\"Times New Roman\", serif; font-style: normal; font-weight: bold; text-decoration: none; font-size: 12pt; }"
				+ " .s6 { color: #120000; font-family:\"Times New Roman\", serif; font-style: normal; font-weight: bold; text-decoration: none; font-size: 12pt; }"
				+ " .s7 { color: black; font-family:\"Times New Roman\", serif; font-style: normal; font-weight: normal; text-decoration: none; font-size: 12pt; }"
				+ " .s8 { color: black; font-family:\"Times New Roman\", serif; font-style: normal; font-weight: normal; text-decoration: none; font-size: 12pt; vertical-align: -2pt; }"
				+ " .s9 { color: black; font-family:\"Times New Roman\", serif; font-style: normal; font-weight: normal; text-decoration: none; font-size: 12pt; }"
				+ " h1 { color: #120000; font-family:\"Times New Roman\", serif; font-style: normal; font-weight: bold; text-decoration: none; font-size: 12pt; }"
				+ " .s10 { color: #2D3499; font-family:\"Times New Roman\", serif; font-style: normal; font-weight: bold; text-decoration: none; font-size: 12pt; }"
				+ " .pt10 { padding-top: 10pt; }" + " .pb10 { padding-bottom: 10pt; }"
				+ " .pb50 { padding-bottom: 50pt; }"
				+ " table, tbody, td {vertical-align: top; overflow: visible; color: black; font-family:\\\"Times New Roman\\\", serif; font-style: normal; font-weight: normal; text-decoration: none; font-size: 10pt; margin:0pt; } "
				// Uncomment below line to add watermark to the pdf
				// + " .watermark { background-image: url(\"data:image/png;base64," +
				// licWatermark + "\");} "
				+ " " + reportStyles + " " + " </style></head><body><div id=\"bg\" class=\"watermark\">"
				+ "<p style=\"padding-left: 5pt;text-indent: 0pt;text-align: left;\"/>";

		if (showLogo) {
			completehtmlContent = completehtmlContent
					+ "<p style=\"text-indent: 0pt;text-align: center;\"><span><table style=\"width:100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\"><tr style=\"display:flex;justify-content:space-between;align-items:center\"><td style=\"padding-left:24pt\"><img width=\"100\" height=\"63\" src=\"data:image/jpg;base64,"
					+ licLogo + "\"/></td>" + "</tr></table></span></p>";
		}
		completehtmlContent = completehtmlContent + "<p style=\"text-indent: 0pt;text-align: left;\"><br/></p>"
				+ reportBody + "";

		String htmlFileLoc = tempPdfLocation + "/" + reportType + referenceNo + ".html";

		System.out.println(htmlFileLoc);
		FileWriter fw = new FileWriter(htmlFileLoc);
		fw.write(completehtmlContent);
		fw.close();

		FileOutputStream fileOutputStream = new FileOutputStream(
				tempPdfLocation + "/" + reportType + referenceNo + ".pdf");
		ITextRenderer renderer = new ITextRenderer();
		renderer.setDocument(new File(htmlFileLoc));
		renderer.layout();
		try {
			renderer.createPDF(fileOutputStream, false);
		} catch (DocumentException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		renderer.finishPDF();

		if (new File(htmlFileLoc).exists()) {
			new File(htmlFileLoc).delete();
		}

		return tempPdfLocation + "/" + reportType + referenceNo + ".pdf";
	}
		
		
		private String fundStatementForV1AndV3(Long policyId,String financialYear) throws IOException {
			InputStream islicLogo = new ClassPathResource("liclogo.png").getInputStream();
			byte[] bytesLogo = IOUtils.toByteArray(islicLogo);
			String licLogo = Base64.getEncoder().encodeToString(bytesLogo);
			
			Object obj = memberMasterRepository.getFundStatementDetails(policyId,financialYear);
			
			Object[] newObject = (Object[]) obj;
			
			String reportBody = "<div style=\" margin: 10px; padding: 10px 25px; border: 1px solid black;\">"
					+ "  <div style=\"display: flex;\">"
					+ "    <span style=\"width: 40%;\">"
//					+"<td style=\"width:25%;\"></td><td style=\"width:50%;text-align:center;\">"
					+ "<img style=\"height: 74px; width: 160px; padding-left: 28px;\" src=\"data:image/jpg;base64," + licLogo + "\"/>"
//							+ "</td>"
					+ "    </span>"
					+ "    <span style=\" width: 60%; \">"
					+ "      <p><b>Life Insurance Corporation of India</b></p>"
					+ "      <p><b>Pension and Group Schemes Dept</b></p>"
					+ "      <p>"+String.valueOf(newObject[2])+"</p>"
					+ "    </span>"
					+ "  </div>"
					+ "  <div style=\"border-top:1px solid black;\"></div>"
					+ "  <div style=\"padding-top: 10px;  \">"
					+ "    <p><b>"+String.valueOf(newObject[2])+"</b></p>"
					+ "    <p><b>"+HtmlEncoder.encode(String.valueOf(newObject[5]))+"</b></p>"
					+ "    <p>"+HtmlEncoder.encode(String.valueOf(newObject[6]))+"</p>"
					+ "    <p>"+HtmlEncoder.encode(String.valueOf(newObject[7]))+"</p>"
					+ "    <p>"+HtmlEncoder.encode(String.valueOf(newObject[8]))+"</p>"
					+ "    <p>"+HtmlEncoder.encode(String.valueOf(newObject[9]))+"-"+String.valueOf(newObject[12])+"</p>"
					+ "    <p>"+String.valueOf(newObject[11])+"</p>"
					+ "    <p>"+String.valueOf(newObject[12])+"</p>"
					+ "  </div>"
					+ "  <div style=\"padding-top: 3px;\">"
					+ "    <p>Dear Sir/Madam,</p>"
					+ "    <div style=\"padding-left: 40px;\">"
					+ "      <p>"
					+ "        <b>"
					+ "          <u> Re: Master Policy No. "+String.valueOf(newObject[3])+" / "+String.valueOf(newObject[1])+" - Certificate of Balance in Fund As On "+String.valueOf(newObject[28])
					+ "          </u>"
					+ "        </b>"
					+ "      </p>"
					+ "    </div>"
					+ "    <p>"
					+ "      We have pleasure in informing you that the interest Rates for the year have been declared and for the year ("+String.valueOf(newObject[14])+""
					+ "      ) the interest rate applicable for your fund is "+String.valueOf(newObject[27])+"."
					+ "    </p>"
					+ "    <p>"
					+ "      The Balance in your Running Account as on "+String.valueOf(newObject[26])+" is as under :"
					+ "    </p>"
					+ "    <div style=\"padding-left: 20px;\">"
					+ "      <p>Opening Balance As On "+String.valueOf(newObject[13])+" :"+String.valueOf(newObject[15])+"</p>"
					+ "      <p>LESS: Opening balance as on 01/04/2021 for exit cases :"+String.valueOf(newObject[16])+"</p>"
					+ "      <p>(details in Annexure I)</p>"
					+ "      <p>Net Opening balance as on "+String.valueOf(newObject[13])+" :"+String.valueOf(newObject[17])+"</p>"
					+ "      <p>Purification On :"+String.valueOf(newObject[18])+"</p>"
					+ "      <p>Purification Off :"+String.valueOf(newObject[19])+"</p>"
					+ "      <p>Revised Opening Balance :"+String.valueOf(newObject[20])+"</p>"
					+ "      <p>Total contribution received during the year [ Ann-II ] :"+String.valueOf(newObject[21])+"</p>"
					+ "      <p>ADD: Equitable interest received during the year [Ann III] :"+String.valueOf(newObject[22])+"</p>"
					+ "      <p>LESS : Contribution for exit cases [ Ann-IV] : "+String.valueOf(newObject[23])+"</p>"
					+ "      <p>NET Contribution during the year : "+String.valueOf(newObject[24])+"</p>"
					+ "      <p>ADD : Interest Credited for the : "+String.valueOf(newObject[25])+"</p>"
					+ "      <p>Year for existing member for the policy as a Whole</p>"
					+ "      <p>Closing Balance As On "+String.valueOf(newObject[28])+" :"+String.valueOf(newObject[26])+" </p>"
					+ "    </div>"
					+ "    <p>"
					+ "      Any discrepancy in the statement may be brought to our notice immediately"
					+ "    </p>"
					+ "    <p>"
					+ "      Thanking you,"
					+ "    </p>"
					+ "    <p>"
					+ "      <b>"
					+ "        Yours Faithfully,"
					+ "      </b>"
					+ "    </p>"
//					+ "    <br>"
					+ "    <p>"
					+ "      <b>"
					+ "        Manager (P &amp; GS)"
					+ "      </b>"
					+ "    </p>"
					+ "    <p>Encl: Annexures #8544; to #8547; and member wise statement</p>"
					+ "  </div>"
					+ "</div>";

			return reportBody.replace("\\", "").replaceAll("\t", "");
		}
		
//		private String fundStatementForV2() throws IOException {
//			InputStream islicLogo = new ClassPathResource("liclogo.png").getInputStream();
//			byte[] bytesLogo = IOUtils.toByteArray(islicLogo);
//			String licLogo = Base64.getEncoder().encodeToString(bytesLogo);
//			String reportBody = "<div style=\" margin: 10px; padding: 10px 25px; \">"
//					+ "  <div style=\"text-align: center; \">"
//					+ "    <span style=\" width: 100%;\">"
//					+ "      <p><b>Life Insurance Corporation of India</b></p>"
//					+ "      <p><b>Pension and Group Schemes Department</b></p>"
//					+ "      <p>BAREILLY DIVISION</p>"
//					+ "    </span>"
//					+ "  </div>"
//					+ "  <div style=\"border-top: 1px solid #000;\"></div>"
//					+ "  <div style=\"display: flex; padding-top: 10px;\">"
//					+ "    <div style=\"width: 50%;\">"
//					+ "      Date :27/07/2022"
//					+ "    </div>"
//					+ "    <div style=\"width: 50%; text-align: end;\">"
//					+ "      Page :&nbsp;&nbsp;&nbsp; 1 &nbsp;&nbsp;"
//					+ "    </div>"
//					+ "  </div>"
//					+ "  <div style=\"text-align: center;\">"
//					+ "    Statement of Policy Account For The Period : &nbsp;&nbsp;&nbsp; 01/04/2022 to 30/06/2022"
//					+ "  </div>"
//					+ "  <div style=\"padding-top: 10px;  \">"
//					+ "    <p>The Trustees</p>"
//					+ "    <p>TRUSTEES EMPLOYEE'S SUPERANNUATION SCHEME RAMPUR DISTILLERY</p>"
//					+ "    <p>BAREILLY ROAD</p>"
//					+ "    <p>RAMPUR</p>"
//					+ "    <p>U.P</p>"
//					+ "    <p>244901</p>"
//					+ "  </div>"
//					+ ""
//					+ "  <div style=\"text-align: center;\">"
//					+ "    <p> Re : NGSCA &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Policy No : 20331763</p>"
//					+ "  </div>"
//					+ "  <div>"
//					+ "    <div style=\"display: flex;\">"
//					+ "      <div style=\"width: 25%;\">"
//					+ "        1. &nbsp;&nbsp;Name of Product"
//					+ "      </div>"
//					+ "      <div style=\"width: 75%;\">"
//					+ "        &nbsp;&nbsp; : &nbsp;&nbsp; New Group Superannuation Cash Accumulation Plan"
//					+ "      </div>"
//					+ "    </div>"
//					+ "    <div style=\"display: flex;\">"
//					+ "      <div style=\"width: 50%;\">"
//					+ "        2. &nbsp;&nbsp;Unique Identification Number"
//					+ "      </div>"
//					+ "      <div style=\"width: 50%;\">"
//					+ "        : &nbsp;&nbsp; &nbsp;&nbsp; 512N274V01"
//					+ "      </div>"
//					+ "    </div>"
//					+ "    <div style=\"display: flex;\">"
//					+ "      <div style=\"width: 50%;\">"
//					+ "        3. &nbsp;&nbsp;Par/Non_par"
//					+ "      </div>"
//					+ "      <div style=\"width: 50%;\">"
//					+ "        : &nbsp;&nbsp; Non_Par"
//					+ "      </div>"
//					+ "    </div>"
//					+ "    <div style=\"display: flex;\">"
//					+ "      <div style=\"width: 50%;\">"
//					+ "        4. &nbsp;&nbsp;Linked/Non_linked"
//					+ "      </div>"
//					+ "      <div style=\"width: 50%;\">"
//					+ "        : &nbsp;&nbsp; Non_linked"
//					+ "      </div>"
//					+ "    </div>"
//					+ "    <div style=\"display: flex;\">"
//					+ "      <div style=\"width: 50%;\">"
//					+ "        5. &nbsp;&nbsp;Minimum Floor Rate of Interest (MFR)"
//					+ "      </div>"
//					+ "      <div style=\"width: 50%;\">"
//					+ "        : &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; 0.5 % pa effective"
//					+ "      </div>"
//					+ "    </div>"
//					+ "    <div style=\"display: flex;\">"
//					+ "      <div style=\"width: 50%;\">"
//					+ "        6. &nbsp;&nbsp;Additional Interest Rate of Interest (AIR)"
//					+ "      </div>"
//					+ "      <div style=\"width: 50%;\">"
//					+ "        : &nbsp;&nbsp; &nbsp;&nbsp;"
//					+ "      </div>"
//					+ "    </div>"
//					+ "    <div style=\"display: flex;\">"
//					+ "      <div style=\"width: 40%;\">"
//					+ "        6c. AIR for quarter ending 30/06/2022 &nbsp;&nbsp; :"
//					+ "      </div>"
//					+ "      <div style=\"width: 60%; text-align: center;\">"
//					+ "        &nbsp;&nbsp;6.54% pa effective"
//					+ "      </div>"
//					+ "    </div>"
//					+ "  </div>"
//					+ "  <div style=\"padding-top: 22px;\">"
//					+ "    <div>"
//					+ "      Statement of policy Account Value Showing Various Components Under The Policy for the period :"
//					+ "    </div>"
//					+ "    <div>"
//					+ "      01/04/2022 &nbsp;&nbsp; to &nbsp;&nbsp; 30/06/2022"
//					+ "    </div>"
//					+ "    <div style=\"padding-top: 22px;\">"
//					+ "      <div style=\"display: flex;\">"
//					+ "        <div style=\"width: 59%;\">"
//					+ "          A. &nbsp;Opening Balance of PAV(*) at the begining"
//					+ "        </div>"
//					+ "        <div style=\"width: 1%;\">"
//					+ "          :"
//					+ "        </div>"
//					+ "        <div style=\"width: 40%; text-align: end; \">"
//					+ "          309010042.375"
//					+ "        </div>"
//					+ "      </div>"
//					+ "      <div style=\"display: flex;\">"
//					+ "        <div style=\"width: 59%;\">"
//					+ "          B. &nbsp;Fund Converted from Old scheme"
//					+ "        </div>"
//					+ "        <div style=\"width: 1%;\">"
//					+ "          :"
//					+ "        </div>"
//					+ "        <div style=\"width: 40%; text-align: end; \">"
//					+ "          .000"
//					+ "        </div>"
//					+ "      </div>"
//					+ "      <div style=\"display: flex;\">"
//					+ "        <div style=\"width: 59%;\">"
//					+ "          C. &nbsp;Premium Received During the Period"
//					+ "        </div>"
//					+ "        <div style=\"width: 1%;\">"
//					+ "          :"
//					+ "        </div>"
//					+ "        <div style=\"width: 40%; text-align: end; \">"
//					+ "          2279593.000"
//					+ "        </div>"
//					+ "      </div>"
//					+ "      <div style=\"display: flex;\">"
//					+ "        <div style=\"width: 37%;\">"
//					+ "          D. &nbsp;Total Claim Paid"
//					+ "        </div>"
//					+ "        <div style=\"width: 22%;\">"
//					+ "          For the Period"
//					+ "        </div>"
//					+ "        <div style=\"width: 1%;\">"
//					+ "          :"
//					+ "        </div>"
//					+ "        <div style=\"width: 40%; text-align: end; \">"
//					+ "          1959357.291"
//					+ "        </div>"
//					+ "      </div>"
//					+ "      <div style=\"display: flex;\">"
//					+ "        <div style=\"width: 37%;\">"
//					+ "          E. &nbsp;Total Equitable / Transfer in"
//					+ "        </div>"
//					+ "        <div style=\"width: 22%;\">"
//					+ "          For the Period"
//					+ "        </div>"
//					+ "        <div style=\"width: 1%;\">"
//					+ "          :"
//					+ "        </div>"
//					+ "        <div style=\"width: 40%; text-align: end; \">"
//					+ "          .000"
//					+ "        </div>"
//					+ "      </div>"
//					+ "      <div style=\"display: flex;\">"
//					+ "        <div style=\"width: 37%;\">"
//					+ "          F. &nbsp;&nbsp;Total Equitable transfer out"
//					+ "        </div>"
//					+ "        <div style=\"width: 22%;\">"
//					+ "          For the Period"
//					+ "        </div>"
//					+ "        <div style=\"width: 1%;\">"
//					+ "          :"
//					+ "        </div>"
//					+ "        <div style=\"width: 40%; text-align: end; \">"
//					+ "          .000"
//					+ "        </div>"
//					+ "      </div>"
//					+ "      <div style=\"display: flex;\">"
//					+ "        <div style=\"width: 59%;\">"
//					+ "          G. &nbsp;Total Mortality Charges (MOC) Deducted For the Period"
//					+ "        </div>"
//					+ "        <div style=\"width: 1%;\">"
//					+ "          :"
//					+ "        </div>"
//					+ "        <div style=\"width: 40%; text-align: end; \">"
//					+ "          .000"
//					+ "        </div>"
//					+ "      </div>"
//					+ "      <div style=\"display: flex;\">"
//					+ "        <div style=\"width: 59%;\">"
//					+ "          H. &nbsp;Total Pol Admin Charges (PAC) Deducted For the Period"
//					+ "        </div>"
//					+ "        <div style=\"width: 1%;\">"
//					+ "          :"
//					+ "        </div>"
//					+ "        <div style=\"width: 40%; text-align: end; \">"
//					+ "          .000"
//					+ "        </div>"
//					+ "      </div>"
//					+ "      <div style=\"display: flex;\">"
//					+ "        <div style=\"width: 59%;\">"
//					+ "          I. &nbsp;&nbsp;Total correction add of fund For prev. quarters"
//					+ "        </div>"
//					+ "        <div style=\"width: 1%;\">"
//					+ "          :"
//					+ "        </div>"
//					+ "        <div style=\"width: 40%; text-align: end; \">"
//					+ "          .000"
//					+ "        </div>"
//					+ "      </div>"
//					+ "      <div style=\"display: flex;\">"
//					+ "        <div style=\"width: 59%;\">"
//					+ "          J. &nbsp;&nbsp;Total correction ded of fund For prev. quarters"
//					+ "        </div>"
//					+ "        <div style=\"width: 1%;\">"
//					+ "          :"
//					+ "        </div>"
//					+ "        <div style=\"width: 40%; text-align: end; \">"
//					+ "          .000"
//					+ "        </div>"
//					+ "      </div>"
//					+ "      <div style=\"display: flex;\">"
//					+ "        <div style=\"width: 59%;\">"
//					+ "          K. &nbsp;Total Fund Management Charges(FMC) Ded For the Period"
//					+ "        </div>"
//					+ "        <div style=\"width: 1%;\">"
//					+ "          :"
//					+ "        </div>"
//					+ "        <div style=\"width: 40%; text-align: end; \">"
//					+ "          306067.895"
//					+ "        </div>"
//					+ "      </div>"
//					+ "      <div style=\"display: flex;\">"
//					+ "        <div style=\"width: 59%;\">"
//					+ "          L. &nbsp;Service Tax On MOC+PAC+FMC For the Period"
//					+ "        </div>"
//					+ "        <div style=\"width: 1%;\">"
//					+ "          :"
//					+ "        </div>"
//					+ "        <div style=\"width: 40%; text-align: end; \">"
//					+ "          55092.222"
//					+ "        </div>"
//					+ "      </div>"
//					+ "      <div style=\"display: flex;\">"
//					+ "        <div style=\"width: 59%;\">"
//					+ "          M.&nbsp;Education Cess + Higher Edu Cess on Service Tax"
//					+ "        </div>"
//					+ "        <div style=\"width: 1%;\">"
//					+ "          :"
//					+ "        </div>"
//					+ "        <div style=\"width: 40%; text-align: end; \">"
//					+ "          .000"
//					+ "        </div>"
//					+ "      </div>"
//					+ "      <div style=\"display: flex;\">"
//					+ "        <div style=\"width: 35%;\">"
//					+ "          N. &nbsp;Interest Amount Credited (MFR)"
//					+ "        </div>"
//					+ "        <div style=\"width: 24%;\">"
//					+ "          For the Period"
//					+ "        </div>"
//					+ "        <div style=\"width: 1%;\">"
//					+ "          :"
//					+ "        </div>"
//					+ "        <div style=\"width: 40%; text-align: end; \">"
//					+ "          382264.265"
//					+ "        </div>"
//					+ "      </div>"
//					+ "      <div style=\"display: flex;\">"
//					+ "        <div style=\"width: 35%;\">"
//					+ "          O. &nbsp;Interest Amount Credited (AIR)"
//					+ "        </div>"
//					+ "        <div style=\"width: 24%;\">"
//					+ "          For the Period"
//					+ "        </div>"
//					+ "        <div style=\"width: 1%;\">"
//					+ "          :"
//					+ "        </div>"
//					+ "        <div style=\"width: 40%; text-align: end; \">"
//					+ "          4890992.061"
//					+ "        </div>"
//					+ "      </div>"
//					+ "      <div style=\"display: flex;\">"
//					+ "        <div style=\"width: 35%;\">"
//					+ "          P. &nbsp;&nbsp;Residual Interest Credited"
//					+ "        </div>"
//					+ "        <div style=\"width: 24%;\">"
//					+ "          For the Period"
//					+ "        </div>"
//					+ "        <div style=\"width: 1%;\">"
//					+ "          :"
//					+ "        </div>"
//					+ "        <div style=\"width: 40%; text-align: end; \">"
//					+ "          .000"
//					+ "        </div>"
//					+ "      </div>"
//					+ "      <div style=\"display: flex;\">"
//					+ "        <div style=\"width: 35%;\">"
//					+ "          Q. &nbsp;MVA Charges applied"
//					+ "        </div>"
//					+ "        <div style=\"width: 24%;\">"
//					+ "          For the Period"
//					+ "        </div>"
//					+ "        <div style=\"width: 1%;\">"
//					+ "          :"
//					+ "        </div>"
//					+ "        <div style=\"width: 40%; text-align: end; \">"
//					+ "          .000"
//					+ "        </div>"
//					+ "      </div>"
//					+ "      <div style=\"display: flex;\">"
//					+ "        <div style=\"width: 35%;\">"
//					+ "          R. &nbsp;Exit Load applied"
//					+ "        </div>"
//					+ "        <div style=\"width: 24%;\">"
//					+ "          For the Period"
//					+ "        </div>"
//					+ "        <div style=\"width: 1%;\">"
//					+ "          :"
//					+ "        </div>"
//					+ "        <div style=\"width: 40%; text-align: end; \">"
//					+ "          .000"
//					+ "        </div>"
//					+ "      </div>"
//					+ "      <div style=\"display: flex; padding-top: 18PX; \">"
//					+ "        <div style=\"width: 70%;\">"
//					+ "          Closing Balance of PAV &nbsp;: &nbsp; (A+B+C-D+E-F-G-H+I-J-K-L-M+N+O+P-Q-R) &nbsp; :"
//					+ "        </div>"
//					+ "        <div style=\"width: 30%; text-align: end; \">"
//					+ "          314242269.438"
//					+ "        </div>"
//					+ "      </div>"
//					+ "    </div>"
//					+ "    <div style=\"padding-top: 18px;\">"
//					+ "      <p>"
//					+ "        Any discrepancy in the statement may be brought to our notice immediately."
//					+ "      </p>"
//					+ "    </div>"
//					+ "    <p>"
//					+ "      Thanking you,"
//					+ "    </p>"
//					+ "    <p>"
//					+ "      <b>"
//					+ "        Yours Faithfully,"
//					+ "      </b>"
//					+ "    </p>"
//					+ ""
//					+ "    <p>"
//					+ "      <b>"
//					+ "        Manager (P &amp; GS)"
//					+ "      </b>"
//					+ "    </p>"
//					+ "    <div>Encl: Ann_I,Ann_II,Ann_III,Ann_IV,Ann_V</div>"
//					+ "    <div>(*) PAV : Policy Account Value</div>"
//					+ "    <div>This is a System generated statement and hence signature is not required</div>"
//					+ "  </div>"
//					+ "</div>"
//					//+ "<!-- -------------------------------------------------------------------------------------------------- -->"
////					+ ""
//					+ "<div style=\" margin: 10px; padding: 10px 25px; \">"
//					+ "  <div style=\"text-align: center; \">"
//					+ "    <span style=\" width: 100%; \">"
//					+ "      <p><b>Life Insurance Corporation of India</b></p>"
//					+ "      <p><b>Pension and Group Schemes Department</b></p>"
//					+ "      <p>BAREILLY DIVISION</p>"
//					+ "    </span>"
//					+ "  </div>"
//					+ "  <div style=\"border-top: 1px solid #000;\"></div>"
//					+ "  <div style=\"display: flex; padding-top: 10px;\">"
//					+ "    <div style=\"width: 50%;\">"
//					+ "      Date :27/07/2022"
//					+ "    </div>"
//					+ "    <div style=\"width: 50%; text-align: end;\">"
//					+ "      Page :&nbsp;&nbsp;&nbsp; 2 &nbsp;&nbsp;"
//					+ "    </div>"
//					+ "  </div>"
//					+ "  <div style=\"text-align: center;\">"
//					+ "    <p> Re : NGSCA &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Policy No : 20331763</p>"
//					+ "  </div>"
//					+ "  <div>"
//					+ "    Statement of Policy Account For The Period : &nbsp;&nbsp;&nbsp; 01/04/2022 to 30/06/2022"
//					+ "  </div>"
//					+ "  <div>"
//					+ "    Customer Code&nbsp;&nbsp;: &nbsp;&nbsp;0220151"
//					+ "  </div>"
//					+ "  <div>"
//					+ "    Customer Name : &nbsp;&nbsp;TRUSTEES EMPLOYEE'S SUPERANNUATION SCHEME RAMPUR DISTILLERY"
//					+ "  </div>"
//					+ "  <div>"
//					+ "    Annual Renewal Date : &nbsp;&nbsp;24/12/2022"
//					+ "  </div>"
//					+ "  <div style=\"text-align: center;\">"
//					+ "    Premium Mode :&nbsp;&nbsp; Q"
//					+ "  </div>"
//					+ "  <div style=\"border-top: 1px dashed black; margin-top: 15px; \"></div>"
//					+ "  <div style=\"padding-top: 10px;\">"
//					+ "    A.Opening Balance Details"
//					+ "  </div>"
//					+ "  <div style=\"display: flex;\">"
//					+ "    <div style=\"width: 20%;\">"
//					+ "      Quarter Ending"
//					+ "    </div>"
//					+ "    <div style=\"width: 20%;\">"
//					+ "      Opening Balance"
//					+ "    </div>"
//					+ "    <div style=\"width: 20%;\">"
//					+ "      Int on MFR"
//					+ "    </div>"
//					+ "    <div style=\"width: 20%;\">"
//					+ "      Int on AIR"
//					+ "    </div>"
//					+ "  </div>"
//					+ "  <div style=\"border-top: 1px dashed black; margin-top: 15px; \"></div>"
//					+ "  <div style=\"display: flex; padding-top: 5px; \">"
//					+ "    <div style=\"width: 20%;\">"
//					+ "      30/06/2022"
//					+ "    </div>"
//					+ "    <div style=\"width: 20%;\">"
//					+ "      309010042.375"
//					+ "    </div>"
//					+ "    <div style=\"width: 20%;\">"
//					+ "      384483.483"
//					+ "    </div>"
//					+ "    <div style=\"width: 20%;\">"
//					+ "      4919308.761"
//					+ "    </div>"
//					+ "  </div>"
////					+ ""
//					+ "  <div style=\"border-top: 1px dashed black; margin-top: 20px; \"></div>"
//					+ "  <div style=\"padding-top: 10px;\">"
//					+ "    C.Details of Premium Adjusted During The Period"
//					+ "  </div>"
//					+ "  <div style=\"border-top: 1px dashed black; margin-top: 10px; \"></div>"
//					+ "  <div style=\"display: flex; padding-top: 10px; \">"
//					+ "    <div style=\"width: 14%;\">"
//					+ "      Receipt No."
//					+ "    </div>"
//					+ "    <div style=\"width: 15%;\">"
//					+ "      Receipt Date"
//					+ "    </div>"
//					+ "    <div style=\"width: 14%;\">"
//					+ "      Adj No"
//					+ "    </div>"
//					+ "    <div style=\"width: 15%;\">"
//					+ "      Adj Date"
//					+ "    </div>"
//					+ "    <div style=\"width: 14%;\">"
//					+ "      Premium"
//					+ "    </div>"
//					+ "    <div style=\"width: 14%;\">"
//					+ "      Int on MFR"
//					+ "    </div>"
//					+ "    <div style=\"width: 14%;\">"
//					+ "      Int on AIR"
//					+ "    </div>"
//					+ "  </div>"
//					+ "  <div style=\"border-top: 1px dashed black; margin-top: 10px; \"></div>"
//					+ ""
//					+ "  <div style=\"display: flex; padding-top: 10px;\">"
//					+ "    <div style=\"width: 14%;\">"
//					+ "      318"
//					+ "    </div>"
//					+ "    <div style=\"width: 15%;\">"
//					+ "      23/06/2022"
//					+ "    </div>"
//					+ "    <div style=\"width: 14%;\">"
//					+ "      294"
//					+ "    </div>"
//					+ "    <div style=\"width: 15%;\">"
//					+ "      29/06/2022"
//					+ "    </div>"
//					+ "    <div style=\"width: 14%;\">"
//					+ "      2279593.00"
//					+ "    </div>"
//					+ "    <div style=\"width: 14%;\">"
//					+ "      218.056"
//					+ "    </div>"
//					+ "    <div style=\"width: 14%;\">"
//					+ "      2771.246"
//					+ "    </div>"
//					+ "  </div>"
//					+ "  <div style=\"border-top: 1px dashed black; margin-top: 20px; \"></div>"
//					+ "  <div style=\"padding-top: 10px;\">"
//					+ "    D.Details of Claim Booked During The Period"
//					+ "  </div>"
//					+ "  <div style=\"border-top: 1px dashed black; margin-top: 10px; \"></div>"
//					+ "  <div style=\"display: flex; padding-top: 10px; \">"
//					+ "    <div style=\"width: 14%;\">"
//					+ "      Voucher No."
//					+ "    </div>"
//					+ "    <div style=\"width: 15%;\">"
//					+ "      Voucher Date"
//					+ "    </div>"
//					+ "    <div style=\"width: 14%;\">"
//					+ "      Pay No"
//					+ "    </div>"
//					+ "    <div style=\"width: 15%;\">"
//					+ "      Pay Date"
//					+ "    </div>"
//					+ "    <div style=\"width: 14%;\">"
//					+ "      Clm amt"
//					+ "    </div>"
//					+ "    <div style=\"width: 14%;\">"
//					+ "      Int on MFR"
//					+ "    </div>"
//					+ "    <div style=\"width: 14%;\">"
//					+ "      Int on AIR"
//					+ "    </div>"
//					+ "  </div>"
//					+ "  <div style=\"border-top: 1px dashed black; margin-top: 10px; \"></div>"
//					+ "  <div style=\"display: flex; padding-top: 10px;\">"
//					+ "    <div style=\"width: 14%;\">"
//					+ "      318"
//					+ "    </div>"
//					+ "    <div style=\"width: 15%;\">"
//					+ "      23/06/2022"
//					+ "    </div>"
//					+ "    <div style=\"width: 14%;\">"
//					+ "      294"
//					+ "    </div>"
//					+ "    <div style=\"width: 15%;\">"
//					+ "      29/06/2022"
//					+ "    </div>"
//					+ "    <div style=\"width: 14%;\">"
//					+ "      2279593.00"
//					+ "    </div>"
//					+ "    <div style=\"width: 14%;\">"
//					+ "      218.056"
//					+ "    </div>"
//					+ "    <div style=\"width: 14%;\">"
//					+ "      2771.246"
//					+ "    </div>"
//					+ "  </div>"
//					+ ""
//					+ "  <div style=\"display: flex; padding-top: 10px;\">"
//					+ "    <div style=\"width: 14%;\">"
//					+ "      318"
//					+ "    </div>"
//					+ "    <div style=\"width: 15%;\">"
//					+ "      23/06/2022"
//					+ "    </div>"
//					+ "    <div style=\"width: 14%;\">"
//					+ "      294"
//					+ "    </div>"
//					+ "    <div style=\"width: 15%;\">"
//					+ "      29/06/2022"
//					+ "    </div>"
//					+ "    <div style=\"width: 14%;\">"
//					+ "      2279593.00"
//					+ "    </div>"
//					+ "    <div style=\"width: 14%;\">"
//					+ "      218.056"
//					+ "    </div>"
//					+ "    <div style=\"width: 14%;\">"
//					+ "      2771.246"
//					+ "    </div>"
//					+ "  </div>"
//					+ ""
//					+ "  <div style=\"border-top: 1px dashed black; margin-top: 20px; \"></div>"
//					+ "</div>"
//					+ ""
//					//+ "<!-- --------------------------------------------------------------------------------------- -->"
//					+ ""
//					+ ""
//					+ "<div style=\" margin: 10px; padding: 10px 25px; \">"
//					+ "  <div style=\"text-align: center; \">"
//					+ "    <span style=\" width: 100%; \">"
//					+ "      <p><b>Life Insurance Corporation of India</b></p>"
//					+ "      <p><b>Pension and Group Schemes Department</b></p>"
//					+ "      <p>BAREILLY DIVISION</p>"
//					+ "    </span>"
//					+ "  </div>"
//					+ "  <div style=\"border-top: 1px solid #000;\"></div>"
//					+ "  <div style=\"display: flex; padding-top: 10px;\">"
//					+ "    <div style=\"width: 50%;\">"
//					+ "      Date :27/07/2022"
//					+ "    </div>"
//					+ "    <div style=\"width: 50%; text-align: end;\">"
//					+ "      Page :&nbsp;&nbsp;&nbsp; 3 &nbsp;&nbsp;"
//					+ "    </div>"
//					+ "  </div>"
//					+ "  <div style=\"text-align: center;\">"
//					+ "    <p> Re : NGSCA &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Policy No : 20331763</p>"
//					+ "  </div>"
//					+ "  <div>"
//					+ "    Statement of Policy Account For The Period : &nbsp;&nbsp;&nbsp; 01/04/2022&nbsp;&nbsp; to&nbsp;&nbsp; 30/06/2022"
//					+ "  </div>"
//					+ "  <div>"
//					+ "    Customer Code&nbsp;&nbsp;: &nbsp;&nbsp;0220151"
//					+ "  </div>"
//					+ "  <div>"
//					+ "    Customer Name : &nbsp;&nbsp;TRUSTEES EMPLOYEE'S SUPERANNUATION SCHEME RAMPUR DISTILLERY"
//					+ "  </div>"
//					+ "  <div>"
//					+ "    Annual Renewal Date : &nbsp;&nbsp;24/12/2022"
//					+ "  </div>"
//					+ "  <div style=\"text-align: center;\">"
//					+ "    Premium Mode :&nbsp;&nbsp; Q"
//					+ "  </div>"
//					+ "  <div style=\"border-top: 1px dashed black; margin-top: 15px; \"></div>"
//					+ "  <div style=\"padding: 10px 0;\">"
//					+ "    Details of Fund Management Charge Deducted During The Period"
//					+ "  </div>"
//					+ "  <div style=\"border-top: 1px dashed black; margin-top: 10px; \"></div>"
//					+ "  <div style=\"display: flex; padding-top: 10px; \">"
//					+ "    <div style=\"width: 25%;\">"
//					+ "      Quarter Ending Date"
//					+ "    </div>"
//					+ "    <div style=\"width: 30%;\">"
//					+ "      Deduction Type"
//					+ "    </div>"
//					+ "    <div style=\"width: 20%;\">"
//					+ "      Deducted on"
//					+ "    </div>"
//					+ "    <div style=\"width: 25%;\">"
//					+ "      Amount"
//					+ "    </div>"
//					+ "  </div>"
//					+ "  <div style=\"border-top: 1px dashed black; margin-top: 20px; \"></div>"
//					+ ""
//					+ "  <div style=\"display: flex; padding-top: 10px;\">"
//					+ "    <div style=\"width: 25%;\">"
//					+ "      30/06/2022"
//					+ "    </div>"
//					+ "    <div style=\"width: 30%;\">"
//					+ "      Fund Management Charge"
//					+ "    </div>"
//					+ "    <div style=\"width: 20%;\">"
//					+ "      30/06/2022"
//					+ "    </div>"
//					+ "    <div style=\"width: 25%;\">"
//					+ "      306067.8953"
//					+ "    </div>"
//					+ "  </div>"
//					+ "  <div style=\"display: flex;\">"
//					+ "    <div style=\"width: 25%;\">"
//					+ "      30/06/2022"
//					+ "    </div>"
//					+ "    <div style=\"width: 30%;\">"
//					+ "      Service Tax on FMC"
//					+ "    </div>"
//					+ "    <div style=\"width: 20%;\">"
//					+ "      30/06/2022"
//					+ "    </div>"
//					+ "    <div style=\"width: 25%;\">"
//					+ "      55092.2220"
//					+ "    </div>"
//					+ "  </div>"
//					+ "  <div style=\"display: flex;\">"
//					+ "    <div style=\"width: 25%;\">"
//					+ "      30/06/2022"
//					+ "    </div>"
//					+ "    <div style=\"width: 30%;\">"
//					+ "      Education + Other cess"
//					+ "    </div>"
//					+ "    <div style=\"width: 20%;\">"
//					+ "      30/06/2022"
//					+ "    </div>"
//					+ "    <div style=\"width: 25%;\">"
//					+ "      .0000"
//					+ "    </div>"
//					+ "  </div>"
//					+ "  <div style=\"border-top: 1px dashed black; margin-top: 20px; \"></div>"
//					+ ""
//					+ "  <div style=\"border-top: 1px dashed black; margin-top: 30px; \"></div>"
//					+ ""
//					+ "  <div style=\"display: flex; padding-top: 50px;\">"
//					+ "    <div style=\"width: 50%; text-align: center;\">"
//					+ "      Prepared By"
//					+ "    </div>"
//					+ "    <div style=\"width: 50%; text-align: center;\">"
//					+ "      Checked By"
//					+ "    </div>"
//					+ "  </div>"
//					+ ""
//					+ "</div>";
//
//			return reportBody.replace("\\", "").replaceAll("\t", "");
//		}
		
		public HttpHeaders getAuthHeaders() {
			HttpHeaders headers = new HttpHeaders();
			headers.add(CommonConstants.AUTHORIZATION, "Bearer ");
			headers.add(CommonConstants.CORELATIONID, UUID.randomUUID().toString());
			headers.add(CommonConstants.BUSINESSCORELATIONID, UUID.randomUUID().toString());
			headers.setContentType(MediaType.APPLICATION_JSON);
			return headers;
		}

		
				

        

}
